"""Generate print.html (every page, in order, one document) and index.html (landing page) from workbook.json.

usage: python tools/build.py          write the generated files
       python tools/build.py --check  exit 1 if a generated file is stale (used by tests/acceptance.py)
page-N.html files are the edited source; print.html and index.html must never be edited by hand.
"""
import html, json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WB = json.loads((ROOT / "workbook.json").read_text(encoding="utf8"))
GENERATED = "<!-- generated by tools/build.py from workbook.json + page-N.html — do not edit -->"


def page_parts(f: Path):
    s = f.read_text(encoding="utf8")
    head = s[s.index("<head>") + 6 : s.index("</head>")]
    links = re.findall(r'<link rel="stylesheet" href="([^"]+)">', head)
    scripts = re.findall(r"<script\b[^>]*>.*?</script>", head, re.S)
    styles = re.findall(r"<style\b[^>]*>.*?</style>", head, re.S)
    main = re.search(r'<main class="a4-page[^"]*"[^>]*>.*?</main>', s, re.S).group(0)
    return links, scripts, styles, main


def build_print():
    links, scripts, styles, mains = [], [], [], []
    for p in WB["pages"]:
        l, sc, st, m = page_parts(ROOT / p["file"])
        links += [x for x in l if x not in links]
        scripts += [x for x in sc if x not in scripts]
        styles += [x for x in st if x not in styles]
        mains.append(m)
    head = "\n".join([f'  <link rel="stylesheet" href="{x}">' for x in links] + [f"  {x}" for x in styles] + [f"  {x}" for x in scripts])
    return (f"<!doctype html>\n{GENERATED}\n<html lang=\"he\" dir=\"rtl\">\n<head>\n  <meta charset=\"utf-8\">\n"
            f"  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n  <title>{html.escape(WB['title'])} — הדפסת החוברת כולה</title>\n"
            f"{head}\n</head>\n<body class=\"print-bundle\">\n" + "\n".join(mains) + "\n</body>\n</html>\n")


def build_index():
    stages = WB.get("stages") or [{"title": "", "from": 1, "to": WB["pageCount"]}]
    cards = []
    for st in stages:
        items = "".join(
            f'<li><a href="{p["file"]}"><span class="n">{p["n"]}</span><span class="t">{html.escape(p["title"])}</span></a></li>'
            for p in WB["pages"] if st["from"] <= p["n"] <= st["to"])
        title = f'<h2>{html.escape(st["title"])} <small>עמודים {st["from"]}–{st["to"]}</small></h2>' if st["title"] else ""
        cards.append(f'<section class="stage">{title}<ol>{items}</ol></section>')
    return f"""<!doctype html>
{GENERATED}
<html lang="he" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{html.escape(WB['title'])}</title>
  <style>
    :root{{--ink:#0f172a;--muted:#475569;--line:#dbe3ee;--accent:{WB.get('accent', '#1d4ed8')};--bg:#f6f8fb;--card:#fff}}
    @media (prefers-color-scheme:dark){{:root{{--ink:#e2e8f0;--muted:#94a3b8;--line:#334155;--bg:#0b1220;--card:#111a2e}}}}
    *{{box-sizing:border-box}} body{{margin:0;background:var(--bg);color:var(--ink);font-family:system-ui,"Segoe UI",Arial,sans-serif}}
    header{{max-width:1100px;margin:0 auto;padding:28px 16px 8px}} h1{{margin:0 0 6px;font-size:30px}} header p{{margin:0;color:var(--muted)}}
    .actions{{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}} .actions a{{border:1px solid var(--accent);color:var(--accent);padding:8px 14px;border-radius:999px;text-decoration:none;font-weight:600}}
    main{{max-width:1100px;margin:0 auto;padding:8px 16px 40px;display:grid;gap:14px}}
    .stage{{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:14px 16px}}
    .stage h2{{margin:0 0 10px;font-size:19px}} .stage h2 small{{color:var(--muted);font-weight:500;font-size:13px;margin-inline-start:6px}}
    ol{{list-style:none;margin:0;padding:0;display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:6px}}
    li a{{display:flex;gap:10px;align-items:center;padding:7px 9px;border-radius:9px;color:inherit;text-decoration:none;border:1px solid transparent}}
    li a:hover{{border-color:var(--line);background:color-mix(in srgb,var(--accent) 6%,transparent)}}
    .n{{flex:0 0 30px;height:30px;border-radius:50%;display:grid;place-items:center;border:1.5px solid var(--accent);color:var(--accent);font-weight:700;font-size:13px}}
    .t{{font-size:14px;line-height:1.3}}
  </style>
</head>
<body>
<header>
  <h1>{html.escape(WB['title'])}</h1>
  <p>{WB['pageCount']} דפי A4 להדפסה · {html.escape(WB.get('subtitle', ''))}</p>
  <div class="actions"><a href="print.html">הדפסת החוברת כולה</a><a href="page-1.html">לעמוד הראשון</a></div>
</header>
<main>
{chr(10).join(cards)}
</main>
</body>
</html>
"""


def main():
    out = {"print.html": build_print(), "index.html": build_index()}
    stale = [name for name, text in out.items() if not (ROOT / name).exists() or (ROOT / name).read_text(encoding="utf8") != text]
    if "--check" in sys.argv:
        if stale:
            print("stale generated files:", ", ".join(stale), "— run python tools/build.py")
            sys.exit(1)
        print("generated files up to date")
        return
    for name, text in out.items():
        (ROOT / name).write_text(text, encoding="utf8")
    print("wrote", ", ".join(out))


if __name__ == "__main__":
    main()
